# Generated by Django 6.0.5 on 2026-06-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('residents', '0001_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('RESIDENT', 'Resident'), ('VISITOR', 'Visitor'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='recognition/snapshots/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cooldown_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_events', to='cameras.camera')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.resident')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitors.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
