import os

DETECTION_FRAME_SKIP = int(os.environ.get("DETECTION_FRAME_SKIP", "3"))
RECOGNITION_FRAME_SKIP = int(os.environ.get("RECOGNITION_FRAME_SKIP", "10"))
LOG_FRAME_SKIP = int(os.environ.get("LOG_FRAME_SKIP", "5"))
STATS_FRAME_SKIP = int(os.environ.get("STATS_FRAME_SKIP", "2"))
JPEG_QUALITY = int(os.environ.get("JPEG_QUALITY", "80"))
INFERENCE_IMGSZ = int(os.environ.get("INFERENCE_IMGSZ", "416"))
STREAM_FPS_SLEEP = float(os.environ.get("STREAM_FPS_SLEEP", "0.033"))
CONFIDENCE_THRESHOLD = float(os.environ.get("CONFIDENCE_THRESHOLD", "0.5"))
RECOGNITION_SIMILARITY_THRESHOLD = float(os.environ.get("RECOGNITION_SIMILARITY_THRESHOLD", "0.65"))
RECOGNITION_COOLDOWN_SECONDS = int(os.environ.get("RECOGNITION_COOLDOWN_SECONDS", "30"))
FACE_DETECTOR_BACKEND = os.environ.get("FACE_DETECTOR_BACKEND", "retinaface")
RECOGNITION_CACHE_TIMEOUT = float(os.environ.get("RECOGNITION_CACHE_TIMEOUT", "300.0"))
RECOGNITION_RETRY_INTERVAL = float(os.environ.get("RECOGNITION_RETRY_INTERVAL", "5.0"))
TRACK_CLEANUP_TIMEOUT = float(os.environ.get("TRACK_CLEANUP_TIMEOUT", "10.0"))
TRACK_HISTORY_MAX_POSITIONS = int(os.environ.get("TRACK_HISTORY_MAX_POSITIONS", "120"))
LOITERING_DWELL_SECONDS = float(os.environ.get("LOITERING_DWELL_SECONDS", "120"))
LOITERING_MOVEMENT_RADIUS = float(os.environ.get("LOITERING_MOVEMENT_RADIUS", "50"))
BEHAVIOUR_EVENT_COOLDOWN_SECONDS = int(os.environ.get("BEHAVIOUR_EVENT_COOLDOWN_SECONDS", "120"))

YOLO_CLASS_IDS = [0, 2, 5, 7]
PERSON_CLASS_IDS = {0}
VEHICLE_CLASS_IDS = {2, 5, 7}
