# Generated by Django 6.0.5 on 2026-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('house_number', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='residents/photos/%Y/%m/%d/')),
                ('face_embedding', models.JSONField(blank=True, default=list)),
                ('enrollment_status', models.CharField(choices=[('PENDING', 'Pending'), ('ENROLLED', 'Enrolled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('enrollment_error', models.TextField(blank=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
