# Generated by Django 6.0.5 on 2026-06-10 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('face_embedding', models.JSONField(blank=True, default=list)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='visitors/snapshots/%Y/%m/%d/')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('is_known', models.BooleanField(default=False)),
                ('associated_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='residents.resident')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
