# Generated by Django 6.0.5 on 2026-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='notification_snapshots/'),
        ),
    ]
