# Generated by Django 6.0.5 on 2026-06-09 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='class_name',
            field=models.CharField(blank=True, help_text='YOLO class name, e.g. person, car', max_length=50),
        ),
        migrations.CreateModel(
            name='CameraLiveStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.PositiveIntegerField(default=0)),
                ('vehicle_count', models.PositiveIntegerField(default=0)),
                ('detected_names', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_stats', to='cameras.camera')),
            ],
        ),
    ]
