# Generated by Django 6.0.5 on 2026-06-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_detection_class_name_cameralivestats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
